@startuml
title Diagrama de Estados - Acciones de Usuarios (Estudiantes y Empleados)\nCiclo de Vida de un Turno - Gestión Comedor Universitario UCV

[*] --> Verificando

state Verificando {
  Verificando : Se verifica en el sistema si hay cupos disponibles y la identidad del usuario
}

state Reservando {
 Reservando : Se le asigna un turno al usuario
 Reservando : Tomando en cuanta el comprobante
 Reservando : Se reduce de capacidad
}

state Consumiendo {
 Consumiendo : Usuario consume la comida
 Consumiendo : Registro de consumo y actualización de insumos
}

state Cancelando {
 Cancelando : Turno cancelado por el usuario
 Cancelando : Liberación de cupo
}

Verificando --> Reservando : Usuario reserva turno\n(Ya verificado comprobante y disponibilidad)
Reservando --> Consumiendo : Usuario presenta comprobante y consume
Reservando --> Cancelando : Usuario cancela reserva

Consumiendo --> [*] : Fin del ciclo para el usuario
Cancelando --> [*] 

note right of Reservando
  Fase donde el usuario reserva el turno.
end note

note left of Consumiendo
  Fase donde el usuario consume el turno reservado.
end note

note right of Cancelando
  Fase alternativa donde el usuario cancela.
end note
@enduml